### ISSUE TITLE
org.graalvm.plugin.compiler no longer published in Gradle Plugin repository

### ISSUE THREAD

**Issue by ridangotaavi** [daemontus/gradle-graal-truffle-plugins#3]
Hi!

Starting from today (or perhaps a couple of days ago), the compiler plugin seems to have been taken down from Gradle Plugin repository (https://plugins.gradle.org/plugin/org.graalvm.plugin.compiler).

Could it be that this plugin no longer recommended and if not, then what are the possible alternatives?

We were using it for running Javascript with stock JDK (https://github.com/graalvm/graal-js-jdk11-gradle-demo)

**Comment by daemontus** [comment]
Hi!

Well, this is a funny situation... I got an email a couple days ago that
the compiler plugin will be removed from the Gradle Plugin repository based
on a request from Oracle, because they don't want to have their code
available there for licensing purposes.

I thought this was ok, because I worked on the plugin as part of an
internship project that, afaik, got abandoned after I left. But I forgot
that the plugin is used in some demos, like this one.

So I think there are three possible ways forward:
 - (1) I'm not following graal that closely anymore, but maybe the plugin
isn't even necessary now? At least at first glance it seems that some of
the functionality can be now accomplished using normal dependencies.
 - (2) Someone at Oracle can figure out where they want to host the plugin,
and then modify the demo such that the plugin is indeed downloaded from the
new location. (the original source for the plugin is still available here:
https://github.com/daemontus/gradle-graal-truffle-plugins)
 - (3) I re-release the plugin under my own name and the demo can still use
it that way. I'm not really planning to develop it much further, but I
guess I could at least move it out of beta.

What do you think is best in your current situation?

(Btw. the main reason for this situation is that at the time, there wasn't
really a proper way to publish a gradle plugin from Oracle infrastructure,
so we just sort of "went for it" because we needed it for the demo)

Sam

**Comment by ridangotaavi** [comment]
It seems that the only issue is that the compiler still needs to be added to upgrade module path.

There is a new demo, where instead of a plugin, this is performed manually: https://github.com/graalvm/polyglot-embedding-demo/blob/main/build.gradle.kts

I didnt manage to get it working exactly like it was done in this new demo (its possible because I use Groovy, but the demo uses Kotlin Script - or it might just be related to my poor Gradle skills), but I did manage to make it work like this:

```
ext.graalVersion = '22.3.3'
ext.graalCompilerPath = "${buildDir}/graalCompiler".toString()

configurations {
    compilerClasspath {
        description = "Graal compiler and its dependencies."
        canBeResolved = true
    }
}

dependencies {
    compilerClasspath "org.graalvm.compiler:compiler:$graalVersion"
}

tasks.register('prepareCompiler', Copy) {
    group = 'graal'
}

afterEvaluate {
    tasks.named('prepareCompiler', Copy, {
        from(configurations.named('compilerClasspath', Configuration).get().getFiles())
        into(graalCompilerPath)
    })
}

tasks.matching { it instanceof JavaForkOptions }.configureEach { task ->
    task.dependsOn('prepareCompiler')

    (task as JavaForkOptions).jvmArgs = [
        "-XX:+UnlockExperimentalVMOptions",
        "-XX:+EnableJVMCI",
        "--upgrade-module-path=${graalCompilerPath}"
    ]
}
```

I did it with an extra task because I need this same output for building a Docker image (otherwise probably not needed).

I guess we can consider this closed as it seems that there arent a lot of people using this plugin and this workaround is good enough for me.

**Comment by daemontus** [comment]
Great, thank you for sorting it out!
